title: "Home"
logo: "assets/images/logo_white_cropped.png"
favicon: "assets/images/logo_notext.svg"

announcements:
- "Coffee session February 12th at the Charles Darwin! ğŸ‰"
- "Next Pizza seminar on the 20th of February!ğŸ• "
