title: "Home"
logo: "assets/images/logo_white_cropped.png"
favicon: "assets/images/logo_notext.svg"

announcements:
- "Pizza seminar this Thursday at 12:00 Marie Curie ğŸ‰"
- "Beer session this 30th of January! ğŸ˜ ğŸ’ƒ ğŸ» "
